server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages

# Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Spring-Doc:
#  version: '@project.version@'